name: test-dpm
run-name: ${{ github.actor }} is running test-dpm
on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup show

      - name: cargo check
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup show

      - name: cargo test
        env:
          PATCH_AUTH_TOKEN: ${{ secrets.PATCH_AUTH_TOKEN }}
          DPM_AUTH_TOKEN: ${{ secrets.DPM_AUTH_TOKEN }}
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_DATABASE: ${{ secrets.SNOWSQL_DATABASE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_SCHEMA }}
        run: cargo test

  nodejs-test:
    name: Static TypeScript Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        working-directory: ./static/nodejs
        run: |
          npm ci
          npm run build --if-present
          npm test

  python-test:
    name: Static Python Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        working-directory: ./static/python
        run: |
          poetry install --no-root
      - name: Run tests
        working-directory: ./static/python
        run: |
          poetry run pytest

  lints:
    name: Format and Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        run: rustup show

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy -- -D warnings
